import Head from 'next/head';
import styled from 'styled-components';
import { CommonCard, CommonCardProps } from '@/components/Card/Card';
import { Button } from 'react-bootstrap';
import { useTheme } from '@/hooks/useTheme';

export default function Home() {
  const cardProps: CommonCardProps = {
    cardType: 'user',
    title: 'Doge Kim',
    subtitle: 'subtitle',
    desc: 'lorem ipsum 나는 로렘입슘 홍길동입니다. 123456',
    imageUrl: 'testdoge.jpg',
  };

  return (
    <>
      <Head>
        <title>ProjectH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        {/* https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/hooks/#custom-hooks */}
        <CommonCard {...cardProps} />
        <CommonCard {...cardProps} />
      </MainContainer>
    </>
  );
}
const MainContainer = styled.main`
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  padding: 6rem;
`;
