import Head from 'next/head';
import styled from 'styled-components';
import { CommonCard, CommonCardProps } from '@/components/Card/Card';
import { MultiItemCarousel } from '@/components/Carousel/Carousel';
import HomeIntroduce from '@/sections/mainPage/introduce';

export default function Home() {
  const cardProps: CommonCardProps = {
    cardType: 'user',
    title: 'Doge Kim',
    subtitle: 'subtitle',
    desc: 'lorem ipsum 나는 로렘입슘 홍길동입니다. 123456',
    imageUrl: 'testdoge.jpg',
  };
  // https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/hooks/#custom-hooks
  return (
    <>
      <Head>
        <title>ProjectH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeIntroduce />
      <MainContainer>
        <MultiItemCarousel title="이 달의 사용자">
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
        </MultiItemCarousel>
        <MultiItemCarousel title="이 달의 추천 사용자">
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
          <CommonCard {...cardProps} />
        </MultiItemCarousel>
        <MultiItemCarousel title="컨텐츠 없을시 예시" />
      </MainContainer>
    </>
  );
}
const MainContainer = styled.main`
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
`;
